/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsSlugRouteImport } from './routes/topics_.$slug'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CommunityThreadsIdRouteImport } from './routes/community_.threads.$id'
import { Route as CommunityEventsIdRouteImport } from './routes/community_.events.$id'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics_/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityThreadsIdRoute = CommunityThreadsIdRouteImport.update({
  id: '/community_/threads/$id',
  path: '/community/threads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityEventsIdRoute = CommunityEventsIdRouteImport.update({
  id: '/community_/events/$id',
  path: '/community/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/collections': typeof CollectionsRoute
  '/community': typeof CommunityRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/topics': typeof TopicsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$slug': typeof PSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/community/events/$id': typeof CommunityEventsIdRoute
  '/community/threads/$id': typeof CommunityThreadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/collections': typeof CollectionsRoute
  '/community': typeof CommunityRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/topics': typeof TopicsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$slug': typeof PSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/community/events/$id': typeof CommunityEventsIdRoute
  '/community/threads/$id': typeof CommunityThreadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/collections': typeof CollectionsRoute
  '/community': typeof CommunityRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/topics': typeof TopicsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$slug': typeof PSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/topics_/$slug': typeof TopicsSlugRoute
  '/community_/events/$id': typeof CommunityEventsIdRoute
  '/community_/threads/$id': typeof CommunityThreadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/collections'
    | '/community'
    | '/leaderboard'
    | '/login'
    | '/privacy'
    | '/settings'
    | '/submit'
    | '/terms'
    | '/topics'
    | '/auth/callback'
    | '/p/$slug'
    | '/profile/$username'
    | '/topics/$slug'
    | '/community/events/$id'
    | '/community/threads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/collections'
    | '/community'
    | '/leaderboard'
    | '/login'
    | '/privacy'
    | '/settings'
    | '/submit'
    | '/terms'
    | '/topics'
    | '/auth/callback'
    | '/p/$slug'
    | '/profile/$username'
    | '/topics/$slug'
    | '/community/events/$id'
    | '/community/threads/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archive'
    | '/collections'
    | '/community'
    | '/leaderboard'
    | '/login'
    | '/privacy'
    | '/settings'
    | '/submit'
    | '/terms'
    | '/topics'
    | '/auth/callback'
    | '/p/$slug'
    | '/profile/$username'
    | '/topics_/$slug'
    | '/community_/events/$id'
    | '/community_/threads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  CollectionsRoute: typeof CollectionsRoute
  CommunityRoute: typeof CommunityRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SubmitRoute: typeof SubmitRoute
  TermsRoute: typeof TermsRoute
  TopicsRoute: typeof TopicsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PSlugRoute: typeof PSlugRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
  CommunityEventsIdRoute: typeof CommunityEventsIdRoute
  CommunityThreadsIdRoute: typeof CommunityThreadsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics_/$slug': {
      id: '/topics_/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/threads/$id': {
      id: '/community_/threads/$id'
      path: '/community/threads/$id'
      fullPath: '/community/threads/$id'
      preLoaderRoute: typeof CommunityThreadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/events/$id': {
      id: '/community_/events/$id'
      path: '/community/events/$id'
      fullPath: '/community/events/$id'
      preLoaderRoute: typeof CommunityEventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  CollectionsRoute: CollectionsRoute,
  CommunityRoute: CommunityRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SubmitRoute: SubmitRoute,
  TermsRoute: TermsRoute,
  TopicsRoute: TopicsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PSlugRoute: PSlugRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  TopicsSlugRoute: TopicsSlugRoute,
  CommunityEventsIdRoute: CommunityEventsIdRoute,
  CommunityThreadsIdRoute: CommunityThreadsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
