/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TopicsSlugRouteImport } from './routes/topics_.$slug'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as DashboardWaitlistRouteImport } from './routes/dashboard/waitlist'
import { Route as DashboardProductsRouteImport } from './routes/dashboard/products'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardMentionsRouteImport } from './routes/dashboard/mentions'
import { Route as DashboardInboxRouteImport } from './routes/dashboard/inbox'
import { Route as DashboardFollowersRouteImport } from './routes/dashboard/followers'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminThreadsRouteImport } from './routes/admin/threads'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminRequestsRouteImport } from './routes/admin/requests'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminMfaEnrollRouteImport } from './routes/admin/mfa-enroll'
import { Route as AdminMfaRouteImport } from './routes/admin/mfa'
import { Route as AdminMakersRouteImport } from './routes/admin/makers'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminCommentsRouteImport } from './routes/admin/comments'
import { Route as CommunityThreadsIdRouteImport } from './routes/community_.threads.$id'
import { Route as CommunityEventsIdRouteImport } from './routes/community_.events.$id'
import { Route as CommunityRequestsIdRouteImport } from './routes/community.requests.$id'
import { Route as DashboardProductsSlugEditRouteImport } from './routes/dashboard/products.$slug.edit'
import { Route as DashboardProductsSlugAnalyticsRouteImport } from './routes/dashboard/products.$slug.analytics'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics_/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWaitlistRoute = DashboardWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMentionsRoute = DashboardMentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFollowersRoute = DashboardFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminThreadsRoute = AdminThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMfaEnrollRoute = AdminMfaEnrollRouteImport.update({
  id: '/mfa-enroll',
  path: '/mfa-enroll',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMfaRoute = AdminMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMakersRoute = AdminMakersRouteImport.update({
  id: '/makers',
  path: '/makers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CommunityThreadsIdRoute = CommunityThreadsIdRouteImport.update({
  id: '/community_/threads/$id',
  path: '/community/threads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityEventsIdRoute = CommunityEventsIdRouteImport.update({
  id: '/community_/events/$id',
  path: '/community/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRequestsIdRoute = CommunityRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => CommunityRoute,
} as any)
const DashboardProductsSlugEditRoute =
  DashboardProductsSlugEditRouteImport.update({
    id: '/$slug/edit',
    path: '/$slug/edit',
    getParentRoute: () => DashboardProductsRoute,
  } as any)
const DashboardProductsSlugAnalyticsRoute =
  DashboardProductsSlugAnalyticsRouteImport.update({
    id: '/$slug/analytics',
    path: '/$slug/analytics',
    getParentRoute: () => DashboardProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/collections': typeof CollectionsRoute
  '/community': typeof CommunityRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/topics': typeof TopicsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/makers': typeof AdminMakersRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/admin/mfa-enroll': typeof AdminMfaEnrollRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/threads': typeof AdminThreadsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/followers': typeof DashboardFollowersRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/mentions': typeof DashboardMentionsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/waitlist': typeof DashboardWaitlistRoute
  '/p/$slug': typeof PSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/community/requests/$id': typeof CommunityRequestsIdRoute
  '/community/events/$id': typeof CommunityEventsIdRoute
  '/community/threads/$id': typeof CommunityThreadsIdRoute
  '/dashboard/products/$slug/analytics': typeof DashboardProductsSlugAnalyticsRoute
  '/dashboard/products/$slug/edit': typeof DashboardProductsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/collections': typeof CollectionsRoute
  '/community': typeof CommunityRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/topics': typeof TopicsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/makers': typeof AdminMakersRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/admin/mfa-enroll': typeof AdminMfaEnrollRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/threads': typeof AdminThreadsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/followers': typeof DashboardFollowersRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/mentions': typeof DashboardMentionsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/waitlist': typeof DashboardWaitlistRoute
  '/p/$slug': typeof PSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/community/requests/$id': typeof CommunityRequestsIdRoute
  '/community/events/$id': typeof CommunityEventsIdRoute
  '/community/threads/$id': typeof CommunityThreadsIdRoute
  '/dashboard/products/$slug/analytics': typeof DashboardProductsSlugAnalyticsRoute
  '/dashboard/products/$slug/edit': typeof DashboardProductsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/collections': typeof CollectionsRoute
  '/community': typeof CommunityRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/topics': typeof TopicsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/makers': typeof AdminMakersRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/admin/mfa-enroll': typeof AdminMfaEnrollRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/threads': typeof AdminThreadsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/followers': typeof DashboardFollowersRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/mentions': typeof DashboardMentionsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/dashboard/waitlist': typeof DashboardWaitlistRoute
  '/p/$slug': typeof PSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/topics_/$slug': typeof TopicsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/community/requests/$id': typeof CommunityRequestsIdRoute
  '/community_/events/$id': typeof CommunityEventsIdRoute
  '/community_/threads/$id': typeof CommunityThreadsIdRoute
  '/dashboard/products/$slug/analytics': typeof DashboardProductsSlugAnalyticsRoute
  '/dashboard/products/$slug/edit': typeof DashboardProductsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/about'
    | '/archive'
    | '/collections'
    | '/community'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/stories'
    | '/submit'
    | '/terms'
    | '/topics'
    | '/verify-otp'
    | '/admin/comments'
    | '/admin/login'
    | '/admin/makers'
    | '/admin/mfa'
    | '/admin/mfa-enroll'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/roles'
    | '/admin/submissions'
    | '/admin/threads'
    | '/admin/users'
    | '/auth/callback'
    | '/dashboard/account'
    | '/dashboard/followers'
    | '/dashboard/inbox'
    | '/dashboard/mentions'
    | '/dashboard/notifications'
    | '/dashboard/products'
    | '/dashboard/waitlist'
    | '/p/$slug'
    | '/profile/$username'
    | '/topics/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/community/requests/$id'
    | '/community/events/$id'
    | '/community/threads/$id'
    | '/dashboard/products/$slug/analytics'
    | '/dashboard/products/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/collections'
    | '/community'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/stories'
    | '/submit'
    | '/terms'
    | '/topics'
    | '/verify-otp'
    | '/admin/comments'
    | '/admin/login'
    | '/admin/makers'
    | '/admin/mfa'
    | '/admin/mfa-enroll'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/roles'
    | '/admin/submissions'
    | '/admin/threads'
    | '/admin/users'
    | '/auth/callback'
    | '/dashboard/account'
    | '/dashboard/followers'
    | '/dashboard/inbox'
    | '/dashboard/mentions'
    | '/dashboard/notifications'
    | '/dashboard/products'
    | '/dashboard/waitlist'
    | '/p/$slug'
    | '/profile/$username'
    | '/topics/$slug'
    | '/admin'
    | '/dashboard'
    | '/community/requests/$id'
    | '/community/events/$id'
    | '/community/threads/$id'
    | '/dashboard/products/$slug/analytics'
    | '/dashboard/products/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/about'
    | '/archive'
    | '/collections'
    | '/community'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/stories'
    | '/submit'
    | '/terms'
    | '/topics'
    | '/verify-otp'
    | '/admin/comments'
    | '/admin/login'
    | '/admin/makers'
    | '/admin/mfa'
    | '/admin/mfa-enroll'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/roles'
    | '/admin/submissions'
    | '/admin/threads'
    | '/admin/users'
    | '/auth/callback'
    | '/dashboard/account'
    | '/dashboard/followers'
    | '/dashboard/inbox'
    | '/dashboard/mentions'
    | '/dashboard/notifications'
    | '/dashboard/products'
    | '/dashboard/waitlist'
    | '/p/$slug'
    | '/profile/$username'
    | '/topics_/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/community/requests/$id'
    | '/community_/events/$id'
    | '/community_/threads/$id'
    | '/dashboard/products/$slug/analytics'
    | '/dashboard/products/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  CollectionsRoute: typeof CollectionsRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StoriesRoute: typeof StoriesRoute
  SubmitRoute: typeof SubmitRoute
  TermsRoute: typeof TermsRoute
  TopicsRoute: typeof TopicsRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PSlugRoute: typeof PSlugRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
  CommunityEventsIdRoute: typeof CommunityEventsIdRoute
  CommunityThreadsIdRoute: typeof CommunityThreadsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/topics_/$slug': {
      id: '/topics_/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/waitlist': {
      id: '/dashboard/waitlist'
      path: '/waitlist'
      fullPath: '/dashboard/waitlist'
      preLoaderRoute: typeof DashboardWaitlistRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/mentions': {
      id: '/dashboard/mentions'
      path: '/mentions'
      fullPath: '/dashboard/mentions'
      preLoaderRoute: typeof DashboardMentionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/followers': {
      id: '/dashboard/followers'
      path: '/followers'
      fullPath: '/dashboard/followers'
      preLoaderRoute: typeof DashboardFollowersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/threads': {
      id: '/admin/threads'
      path: '/threads'
      fullPath: '/admin/threads'
      preLoaderRoute: typeof AdminThreadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mfa-enroll': {
      id: '/admin/mfa-enroll'
      path: '/mfa-enroll'
      fullPath: '/admin/mfa-enroll'
      preLoaderRoute: typeof AdminMfaEnrollRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mfa': {
      id: '/admin/mfa'
      path: '/mfa'
      fullPath: '/admin/mfa'
      preLoaderRoute: typeof AdminMfaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/makers': {
      id: '/admin/makers'
      path: '/makers'
      fullPath: '/admin/makers'
      preLoaderRoute: typeof AdminMakersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/community_/threads/$id': {
      id: '/community_/threads/$id'
      path: '/community/threads/$id'
      fullPath: '/community/threads/$id'
      preLoaderRoute: typeof CommunityThreadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/events/$id': {
      id: '/community_/events/$id'
      path: '/community/events/$id'
      fullPath: '/community/events/$id'
      preLoaderRoute: typeof CommunityEventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/requests/$id': {
      id: '/community/requests/$id'
      path: '/requests/$id'
      fullPath: '/community/requests/$id'
      preLoaderRoute: typeof CommunityRequestsIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/dashboard/products/$slug/edit': {
      id: '/dashboard/products/$slug/edit'
      path: '/$slug/edit'
      fullPath: '/dashboard/products/$slug/edit'
      preLoaderRoute: typeof DashboardProductsSlugEditRouteImport
      parentRoute: typeof DashboardProductsRoute
    }
    '/dashboard/products/$slug/analytics': {
      id: '/dashboard/products/$slug/analytics'
      path: '/$slug/analytics'
      fullPath: '/dashboard/products/$slug/analytics'
      preLoaderRoute: typeof DashboardProductsSlugAnalyticsRouteImport
      parentRoute: typeof DashboardProductsRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMakersRoute: typeof AdminMakersRoute
  AdminMfaRoute: typeof AdminMfaRoute
  AdminMfaEnrollRoute: typeof AdminMfaEnrollRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminThreadsRoute: typeof AdminThreadsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCommentsRoute: AdminCommentsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMakersRoute: AdminMakersRoute,
  AdminMfaRoute: AdminMfaRoute,
  AdminMfaEnrollRoute: AdminMfaEnrollRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminThreadsRoute: AdminThreadsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardProductsRouteChildren {
  DashboardProductsSlugAnalyticsRoute: typeof DashboardProductsSlugAnalyticsRoute
  DashboardProductsSlugEditRoute: typeof DashboardProductsSlugEditRoute
}

const DashboardProductsRouteChildren: DashboardProductsRouteChildren = {
  DashboardProductsSlugAnalyticsRoute: DashboardProductsSlugAnalyticsRoute,
  DashboardProductsSlugEditRoute: DashboardProductsSlugEditRoute,
}

const DashboardProductsRouteWithChildren =
  DashboardProductsRoute._addFileChildren(DashboardProductsRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardFollowersRoute: typeof DashboardFollowersRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardMentionsRoute: typeof DashboardMentionsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProductsRoute: typeof DashboardProductsRouteWithChildren
  DashboardWaitlistRoute: typeof DashboardWaitlistRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardFollowersRoute: DashboardFollowersRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardMentionsRoute: DashboardMentionsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProductsRoute: DashboardProductsRouteWithChildren,
  DashboardWaitlistRoute: DashboardWaitlistRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface CommunityRouteChildren {
  CommunityRequestsIdRoute: typeof CommunityRequestsIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityRequestsIdRoute: CommunityRequestsIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  CollectionsRoute: CollectionsRoute,
  CommunityRoute: CommunityRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StoriesRoute: StoriesRoute,
  SubmitRoute: SubmitRoute,
  TermsRoute: TermsRoute,
  TopicsRoute: TopicsRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PSlugRoute: PSlugRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  TopicsSlugRoute: TopicsSlugRoute,
  CommunityEventsIdRoute: CommunityEventsIdRoute,
  CommunityThreadsIdRoute: CommunityThreadsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
